title = "Cupertino Blog"
baseURL = "/"
languageCode = "en-us"
resourceDir = "../resources"
theme = "ananke"
themesDir = "themes"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Cupertino Blog"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "images/CUPFLB.png"
  site_logo = "images/Cupertino Forum Banner.png"
  description = "A diplomatic forum for micronational cooperation, diplomacy, and socializing."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 6

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/cupertino_org"
[[params.ananke_socials]]
name = "discord-black"
url = "https://discord.gg/7FFunBaT6m"

[menu]
[[menu.main]]
  name = 'Posts'
  url = '/post'
  weight = 20
[[menu.main]]
  name = 'Guides'
  url = '/guides'
  weight = 30
